domain_path: D:\ProyectosVivado\02_Prueba_EMIO_workspace\prueba_EMIO\export\prueba_EMIO\sw\standalone_ps7_cortexa9_0
app_src_dir: D:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
