domain_path: D:\ProyectosVivado\03_AXI_Peripherals_QSPI_App\fsbl_master\export\fsbl_master\sw\standalone_ps7_cortexa9_0
app_src_dir: D:\Xilinx\Vitis\2023.2\data\embeddedsw\lib\sw_apps\zynq_fsbl
template: zynq_fsbl
